package consts

const (
	UserTableName       = "user"
	VideoTableName      = "video"
	CommentTableName    = "comment"
	MessageTableName    = "message"
	SecretKey           = "secret key"
	IdentityKey         = "id"
	Total               = "total"
	ApiServiceName      = "douyinapi"
	UserServiceName     = "douyinuser"
	VideoServiceName    = "douyinvideo"
	CommentServiceName  = "douyincomment"
	MessageServiceName  = "message"
	RelationTableName   = "relation"
	FavoriteTableName   = "favorite"
	RelationServiceName = "relation"
	FavoriteServiceName = "douyinfavorite"
	MySQLDefaultDSN     = "douyin:douyin@tcp(localhost:3306)/douyin?charset=utf8&parseTime=True&loc=Local"
	TCP                 = "tcp"
	UserServiceAddr     = ":9000"
	VideoServiceAddr    = ":10000"
	RelationServiceAddr = ":12000"
	CommentServiceAddr  = ":13000"
	FavoriteServiceAddr = ":11000"
	MessageServiceAddr  = ":14000"
	ExportEndpoint      = ":4317"
	ETCDAddress         = "127.0.0.1:2379"
	DefaultLimit        = 10
	CDNURL              = "http://192.168.43.235:8080/"
	StaticRoot          = "/home/mao/Desktop/douyin/"
	Endpoint            = "oss-cn-qingdao.aliyuncs.com"
	AKID                = "LTAI5tA3AdzJpEjDcukRT4Ks"
	AKS                 = "aYjN0qjcpzTwAqUzngVB4HNWMLsrTl"
	Bucket              = "jaxdy"
)
